node {
        stage('Stage1') {
                echo "Stage1 executing"
                sleep 10
        }
        stage('Stage2') {
                echo "Stage2 executing"
                sleep 10
        }
        stage('Stage3') {
                echo "Stage3 executing"
                sleep 10
        }
}

