node{
        stage('Running in Parallel') {
                parallel 'Parallel1': {
                        echo "Parallel1 executing"
                        sleep 10
                },
                'Parallel2': {
                        echo "Parallel2 executing"
                        sleep 10
                },
                'Parallel3': {
                        echo "Parallel3 executing"
                        sleep 10
                },
                failFast : true
        }
}

